<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProvisioningAI.Data\ProvisioningAI.Data.csproj" />
    <ProjectReference Include="..\ProvisioningAI.MFilesConnectors\ProvisioningAI.MFilesConnectors.csproj" />
    <ProjectReference Include="..\ProvisioningAI.Discovery\ProvisioningAI.Discovery.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
  </ItemGroup>

</Project>
