// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvisioningAI.Data;

#nullable disable

namespace ProvisioningAI.Data.Migrations
{
    [DbContext(typeof(ProvisioningAiDbContext))]
    [Migration("20260726134059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProvisioningAI.Data.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("VaultGuid");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectTypeGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.HasIndex("VaultGuid", "ObjectTypeGuid");

                    b.ToTable("Classes", t =>
                        {
                            t.HasCheckConstraint("CK_Classes_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_Classes_ObjectTypeGuid_Format", "length(\"ObjectTypeGuid\") = 38 AND \"ObjectTypeGuid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_Classes_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.DiscoveryScan", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictsDetectedJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntegrationsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectsFound")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScanDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScanId");

                    b.HasIndex("VaultGuid");

                    b.ToTable("DiscoveryScans", t =>
                        {
                            t.HasCheckConstraint("CK_DiscoveryScans_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.IntegrationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRewireable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("IntegrationPoints", t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationPoints_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_IntegrationPoints_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.MappingTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntegrationPointsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("TemplateId");

                    b.HasIndex("VaultGuid");

                    b.ToTable("MappingTemplates", t =>
                        {
                            t.HasCheckConstraint("CK_MappingTemplates_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.NamedAcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AclDefinitionJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("NamedAcls", t =>
                        {
                            t.HasCheckConstraint("CK_NamedAcls_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_NamedAcls_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.NamedValueStorage", b =>
                {
                    b.Property<string>("VaultGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("unclassified");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValueChangedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("VaultGuid", "Module", "Key");

                    b.HasIndex("LastSeenScanId");

                    b.ToTable("NamedValueStorages", t =>
                        {
                            t.HasCheckConstraint("CK_NamedValueStorage_Classification", "Classification IN ('customer', 'static', 'unclassified', 'artifact')");

                            t.HasCheckConstraint("CK_NamedValueStorages_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RealObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("ObjectTypes", t =>
                        {
                            t.HasCheckConstraint("CK_ObjectTypes_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_ObjectTypes_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("Properties", t =>
                        {
                            t.HasCheckConstraint("CK_Properties_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_Properties_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("UserGroups", t =>
                        {
                            t.HasCheckConstraint("CK_UserGroups_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_UserGroups_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.ValueList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("ValueLists", t =>
                        {
                            t.HasCheckConstraint("CK_ValueLists_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_ValueLists_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.ValueListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueListGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.HasIndex("VaultGuid", "ValueListGuid");

                    b.ToTable("ValueListItems", t =>
                        {
                            t.HasCheckConstraint("CK_ValueListItems_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_ValueListItems_ValueListGuid_Format", "length(\"ValueListGuid\") = 38 AND \"ValueListGuid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_ValueListItems_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.VaultStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VaultGuid")
                        .IsUnique();

                    b.ToTable("VaultStructures", t =>
                        {
                            t.HasCheckConstraint("CK_VaultStructures_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.View", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("Views", t =>
                        {
                            t.HasCheckConstraint("CK_Views_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_Views_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.ToTable("Workflows", t =>
                        {
                            t.HasCheckConstraint("CK_Workflows_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_Workflows_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.WorkflowState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "Guid")
                        .IsUnique();

                    b.HasIndex("VaultGuid", "WorkflowGuid");

                    b.ToTable("WorkflowStates", t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowStates_Guid_Format", "length(\"Guid\") = 38 AND \"Guid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_WorkflowStates_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_WorkflowStates_WorkflowGuid_Format", "length(\"WorkflowGuid\") = 38 AND \"WorkflowGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.WorkflowTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actions")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromStateGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardConditions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSeenScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToStateGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenScanId");

                    b.HasIndex("VaultGuid", "FromStateGuid");

                    b.HasIndex("VaultGuid", "ToStateGuid");

                    b.HasIndex("VaultGuid", "WorkflowGuid", "MFilesId")
                        .IsUnique();

                    b.ToTable("WorkflowTransitions", t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowTransitions_FromStateGuid_Format", "length(\"FromStateGuid\") = 38 AND \"FromStateGuid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_WorkflowTransitions_ToStateGuid_Format", "length(\"ToStateGuid\") = 38 AND \"ToStateGuid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_WorkflowTransitions_VaultGuid_Format", "length(\"VaultGuid\") = 38 AND \"VaultGuid\" LIKE '{%}'");

                            t.HasCheckConstraint("CK_WorkflowTransitions_WorkflowGuid_Format", "length(\"WorkflowGuid\") = 38 AND \"WorkflowGuid\" LIKE '{%}'");
                        });
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.AuditLog", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.Class", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvisioningAI.Data.Models.ObjectType", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid", "ObjectTypeGuid")
                        .HasPrincipalKey("VaultGuid", "Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.DiscoveryScan", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.IntegrationPoint", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.MappingTemplate", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.NamedAcl", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.NamedValueStorage", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.ObjectType", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.Property", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.UserGroup", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.ValueList", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.ValueListItem", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvisioningAI.Data.Models.ValueList", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid", "ValueListGuid")
                        .HasPrincipalKey("VaultGuid", "Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.View", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.Workflow", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.WorkflowState", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvisioningAI.Data.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid", "WorkflowGuid")
                        .HasPrincipalKey("VaultGuid", "Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProvisioningAI.Data.Models.WorkflowTransition", b =>
                {
                    b.HasOne("ProvisioningAI.Data.Models.DiscoveryScan", null)
                        .WithMany()
                        .HasForeignKey("LastSeenScanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProvisioningAI.Data.Models.VaultStructure", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid")
                        .HasPrincipalKey("VaultGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvisioningAI.Data.Models.WorkflowState", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid", "FromStateGuid")
                        .HasPrincipalKey("VaultGuid", "Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvisioningAI.Data.Models.WorkflowState", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid", "ToStateGuid")
                        .HasPrincipalKey("VaultGuid", "Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProvisioningAI.Data.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("VaultGuid", "WorkflowGuid")
                        .HasPrincipalKey("VaultGuid", "Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
